version: 2

models:
  - name: silver_food_prices
    columns:
      - name: price_date
        tests:
          - not_null
      - name: region_name
        tests:
          - not_null
      - name: commodity_name
        tests:
          - not_null
      - name: price_php
        tests:
          - not_null

  - name: silver_psa_cpi
    columns:
      - name: region_name
        tests:
          - not_null
      - name: cpi_year
        tests:
          - not_null
      - name: cpi_value
        tests:
          - not_null

  - name: dim_region
    columns:
      - name: region_key
        tests:
          - not_null
          - unique
      - name: region_name
        tests:
          - not_null
          - unique

  - name: dim_commodity
    columns:
      - name: commodity_key
        tests:
          - not_null
          - unique

  - name: dim_date
    columns:
      - name: date_key
        tests:
          - not_null
          - unique

  - name: dim_market
    columns:
      - name: market_key
        tests:
          - not_null
          - unique

  - name: fact_food_prices
    columns:
      - name: price_php
        tests:
          - not_null
      - name: region_name
        tests:
          - not_null
      - name: price_date
        tests:
          - not_null